/**
 * Manufacturer-Specific DTC Codes Database
 * Build #2 - WiseDrive OBD-II DTC Scanner
 * 
 * This database contains manufacturer-specific diagnostic codes that are not
 * part of the standard OBD-II SAE codes. These codes typically start with P1xxx, P3xxx,
 * B1xxx, C1xxx, U1xxx ranges.
 */

export interface ManufacturerDTCEntry {
  code: string;
  description: string;
  manufacturers: string[]; // manufacturer IDs that use this code
  systems?: string[]; // affected systems like 'Engine', 'Transmission', 'ABS', etc.
  yearRange?: { start?: number; end?: number }; // applicable year range
}

// Manufacturer-specific DTC codes database
export const MANUFACTURER_DTC_CODES: ManufacturerDTCEntry[] = [
  // ==================== TOYOTA / LEXUS SPECIFIC ====================
  { code: 'P1100', description: 'Barometric Pressure Sensor Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1120', description: 'Accelerator Pedal Position Sensor Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1121', description: 'Accelerator Pedal Position Sensor Range/Performance', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1125', description: 'Throttle Control Motor Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1127', description: 'ETCS Actuator Power Source Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1128', description: 'Throttle Control Motor Lock', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1129', description: 'Electric Throttle Control System', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1130', description: 'Air/Fuel Sensor Circuit Range/Performance (Bank 1 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1133', description: 'Air/Fuel Sensor Circuit Response (Bank 1 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1135', description: 'Air/Fuel Sensor Heater Circuit Response (Bank 1 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1150', description: 'Air/Fuel Sensor Circuit Range/Performance (Bank 2 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1153', description: 'Air/Fuel Sensor Circuit Response (Bank 2 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1155', description: 'Air/Fuel Sensor Heater Circuit Response (Bank 2 Sensor 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1200', description: 'Fuel Pump Relay Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1300', description: 'Igniter Circuit (Bank 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1305', description: 'Igniter Circuit (Bank 2)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1310', description: 'Igniter Circuit No.2', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1315', description: 'Igniter Circuit No.3', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1320', description: 'Igniter Circuit No.4', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1325', description: 'Igniter Circuit No.5', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1330', description: 'Igniter Circuit No.6', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1335', description: 'Crankshaft Position Sensor Circuit (During Engine Running)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1340', description: 'Igniter Circuit No.7', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1345', description: 'Igniter Circuit No.8', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1346', description: 'Variable Valve Timing Sensor (Bank 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1349', description: 'Variable Valve Timing System (Bank 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1350', description: 'Variable Valve Timing Sensor (Bank 2)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1354', description: 'Variable Valve Timing System (Bank 2)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1400', description: 'Sub-Throttle Position Sensor', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1401', description: 'Sub-Throttle Position Sensor Range/Performance', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1410', description: 'EGR Valve Position Sensor Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1411', description: 'EGR Valve Position Sensor Range/Performance', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1500', description: 'Starter Signal Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1510', description: 'Air Volume Too Low With Supercharger On', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1520', description: 'Stop Lamp Switch Signal', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1565', description: 'Cruise Control Main Switch Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1600', description: 'ECM Battery Backup Circuit', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1605', description: 'Knock Control CPU', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1633', description: 'ECM', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1656', description: 'OCV Circuit (Bank 1)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1663', description: 'OCV Circuit (Bank 2)', manufacturers: ['toyota', 'lexus'] },
  { code: 'P1780', description: 'Park/Neutral Position Switch', manufacturers: ['toyota', 'lexus'] },

  // ==================== HONDA / ACURA SPECIFIC ====================
  { code: 'P1106', description: 'Barometric Pressure Circuit Range/Performance', manufacturers: ['honda', 'acura'] },
  { code: 'P1107', description: 'Barometric Pressure Circuit Low Input', manufacturers: ['honda', 'acura'] },
  { code: 'P1108', description: 'Barometric Pressure Circuit High Input', manufacturers: ['honda', 'acura'] },
  { code: 'P1116', description: 'ECT Sensor Circuit Range/Performance', manufacturers: ['honda', 'acura'] },
  { code: 'P1121', description: 'Throttle Position Lower Than Expected', manufacturers: ['honda', 'acura'] },
  { code: 'P1122', description: 'Throttle Position Higher Than Expected', manufacturers: ['honda', 'acura'] },
  { code: 'P1128', description: 'MAP Lower Than Expected', manufacturers: ['honda', 'acura'] },
  { code: 'P1129', description: 'MAP Higher Than Expected', manufacturers: ['honda', 'acura'] },
  { code: 'P1157', description: 'Air/Fuel Ratio (A/F) Sensor (Sensor 1) AFS Circuit Low Voltage', manufacturers: ['honda', 'acura'] },
  { code: 'P1158', description: 'Air/Fuel Ratio (A/F) Sensor (Sensor 1) AFS Circuit High Voltage', manufacturers: ['honda', 'acura'] },
  { code: 'P1162', description: 'LAF Sensor (Sensor 1) Circuit Slow Response', manufacturers: ['honda', 'acura'] },
  { code: 'P1163', description: 'LAF Sensor (Sensor 1) Circuit Slow Response', manufacturers: ['honda', 'acura'] },
  { code: 'P1164', description: 'Air/Fuel Ratio (A/F) Sensor (Sensor 1) LABEL Circuit Range/Performance', manufacturers: ['honda', 'acura'] },
  { code: 'P1166', description: 'Air/Fuel Ratio (A/F) Sensor (Sensor 1) Heater System Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1167', description: 'Air/Fuel Ratio (A/F) Sensor (Sensor 1) Heater System Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1253', description: 'VTEC System (Bank 2)', manufacturers: ['honda', 'acura'] },
  { code: 'P1257', description: 'VTEC System (Bank 1)', manufacturers: ['honda', 'acura'] },
  { code: 'P1259', description: 'VTEC System (Bank 1)', manufacturers: ['honda', 'acura'] },
  { code: 'P1297', description: 'Electrical Load Detector Circuit Low Input', manufacturers: ['honda', 'acura'] },
  { code: 'P1298', description: 'Electrical Load Detector Circuit High Input', manufacturers: ['honda', 'acura'] },
  { code: 'P1336', description: 'CSF Sensor Intermittent Interruption', manufacturers: ['honda', 'acura'] },
  { code: 'P1337', description: 'CSF Sensor No Signal', manufacturers: ['honda', 'acura'] },
  { code: 'P1359', description: 'CKP/TDC Sensor Connector Disconnection', manufacturers: ['honda', 'acura'] },
  { code: 'P1361', description: 'TDC Sensor Intermittent Interruption', manufacturers: ['honda', 'acura'] },
  { code: 'P1362', description: 'TDC Sensor No Signal', manufacturers: ['honda', 'acura'] },
  { code: 'P1366', description: 'TDC Sensor No.2 Intermittent Interruption', manufacturers: ['honda', 'acura'] },
  { code: 'P1367', description: 'TDC Sensor No.2 No Signal', manufacturers: ['honda', 'acura'] },
  { code: 'P1381', description: 'CYP Sensor Intermittent Interruption', manufacturers: ['honda', 'acura'] },
  { code: 'P1382', description: 'CYP Sensor No Signal', manufacturers: ['honda', 'acura'] },
  { code: 'P1456', description: 'EVAP Emission Control System Leak Detected (Fuel Tank System)', manufacturers: ['honda', 'acura'] },
  { code: 'P1457', description: 'EVAP Emission Control System Leak Detected (Control Canister System)', manufacturers: ['honda', 'acura'] },
  { code: 'P1491', description: 'EGR Valve Lift Insufficient Detected', manufacturers: ['honda', 'acura'] },
  { code: 'P1498', description: 'EGR Valve Lift Sensor High Voltage', manufacturers: ['honda', 'acura'] },
  { code: 'P1508', description: 'IAC Valve Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1509', description: 'IAC Valve Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1519', description: 'IAC Valve Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1607', description: 'ECM/PCM Internal Circuit A', manufacturers: ['honda', 'acura'] },
  { code: 'P1705', description: 'Transmission Range Switch Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1706', description: 'Transmission Range Switch Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1738', description: '2nd Clutch Pressure Switch Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1739', description: '3rd Clutch Pressure Switch Circuit', manufacturers: ['honda', 'acura'] },
  { code: 'P1768', description: 'A/T FI Data Line', manufacturers: ['honda', 'acura'] },

  // ==================== NISSAN / INFINITI SPECIFIC ====================
  { code: 'P1105', description: 'MAP/BARO Switch Solenoid Valve', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1110', description: 'Intake Valve Timing Control Solenoid (Bank 2)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1111', description: 'Intake Valve Timing Control (Bank 2)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1112', description: 'Intake Valve Timing Control (Bank 2) Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1115', description: 'Engine Coolant Temperature Signal Missing', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1120', description: 'Secondary Throttle Position Sensor Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1122', description: 'Secondary Throttle Position Sensor Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1125', description: 'Tandem Throttle Position Sensor', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1126', description: 'Throttle Control Motor Relay Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1130', description: 'Swirl Control Valve Control Solenoid Valve', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1135', description: 'Intake Valve Timing Control Solenoid (Bank 1)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1138', description: 'Intake Valve Timing Control Position Sensor Circuit (Bank 1)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1140', description: 'Intake Valve Timing Control (Bank 1)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1145', description: 'Intake Valve Timing Control Position Sensor Circuit (Bank 1)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1148', description: 'Closed Loop Control Function (Bank 1)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1168', description: 'Closed Loop Control Function (Bank 2)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1210', description: 'Traction Control Signal Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1211', description: 'ABS/TCS Control Unit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1217', description: 'Engine Over Temperature', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1220', description: 'Fuel Pump Control Module', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1320', description: 'Ignition Signal', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1336', description: 'Crankshaft Position Sensor (CKPS)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1400', description: 'EGRC Solenoid Valve', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1401', description: 'EGR Temperature Sensor', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1402', description: 'EGR System', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1440', description: 'EVAP Control System (Small Leak)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1441', description: 'Vacuum Cut Valve Bypass Valve', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1443', description: 'EVAP Canister Control Vacuum Switch Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1444', description: 'EVAP Canister Purge Volume Control Valve Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1445', description: 'EVAP Canister Purge Volume Control Valve Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1446', description: 'EVAP Canister Vent Control Valve Close', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1447', description: 'EVAP Control System Purge Flow Monitoring', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1448', description: 'EVAP Canister Vent Control Valve Open', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1490', description: 'Vacuum Cut Valve Bypass Valve Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1491', description: 'Vacuum Cut Valve Bypass Valve Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1492', description: 'EVAP Canister Purge Control/Solenoid Valve Circuit', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1605', description: 'TCM A/T Diagnostic Communication Line', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1705', description: 'Throttle Position Sensor (Switch)', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1706', description: 'Park/Neutral Position Switch', manufacturers: ['nissan', 'infiniti'] },
  { code: 'P1760', description: 'Overrun Clutch Solenoid Valve', manufacturers: ['nissan', 'infiniti'] },

  // ==================== HYUNDAI / KIA / GENESIS SPECIFIC ====================
  { code: 'P1105', description: 'Fuel Pressure Regulator', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1106', description: 'Intake Manifold Pressure Sensor Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1107', description: 'Intake Manifold Pressure Sensor High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1114', description: 'Engine Coolant Temperature Sensor Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1115', description: 'Engine Coolant Temperature Sensor High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1117', description: 'Intake Air Temperature Sensor Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1118', description: 'Intake Air Temperature Sensor High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1121', description: 'Throttle Position Sensor High RPM', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1123', description: 'Long Term Fuel Trim Add Air (Bank 1)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1124', description: 'Long Term Fuel Trim Add Air (Bank 2)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1127', description: 'Long Term Fuel Trim (Bank 1)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1128', description: 'Long Term Fuel Trim (Bank 2)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1151', description: 'Heated Oxygen Sensor Slow Response (Bank 2)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1152', description: 'Heated Oxygen Sensor Bank2 Lean/Rich Shift', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1154', description: 'Heated Oxygen Sensor Stuck (Bank 2 Sensor 1)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1159', description: 'Fuel Trim Correction (Bank 2)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1166', description: 'Heated Oxygen Sensor (Bank 2 Sensor 2) Min/Max', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1170', description: 'Front Heated Oxygen Sensor Stuck (Bank 1)', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1195', description: 'EGR Pressure Sensor Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1196', description: 'EGR Pressure Sensor High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1250', description: 'Pressure Regulator Control Solenoid Valve', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1252', description: 'Pressure Regulator Control Solenoid Valve', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1307', description: 'Chassis Acceleration Sensor Signal High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1308', description: 'Chassis Acceleration Sensor Signal Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1345', description: 'Crankshaft/Camshaft Sensor Range/Performance', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1386', description: 'Knock Sensor Control Zero Test', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1402', description: 'EGR Valve Position Sensor Circuit', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1449', description: 'Canister Drain Cut Valve', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1450', description: 'Excessive Vacuum Leak', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1455', description: 'Fuel Tank Sending Unit', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1457', description: 'Purge Solenoid Valve Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1458', description: 'Canister Close Valve', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1486', description: 'Thermostat Heater Control Circuit', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1505', description: 'Idle Air Control Motor Opening Coil Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1506', description: 'Idle Air Control Motor Opening Coil High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1507', description: 'Idle Air Control Motor Closing Coil Low', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1508', description: 'Idle Air Control Motor Closing Coil High', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1523', description: 'Variable Intake System Motor', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1586', description: 'A/T-M/T Codification', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1608', description: 'PCM Internal Error', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1610', description: 'Immobilizer Communication Error', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1611', description: 'MIL Request Signal Circuit', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1614', description: 'Immobilizer ECU Signal', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1624', description: 'MIL Request Signal from TCM', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1693', description: 'MIL Circuit', manufacturers: ['hyundai', 'kia', 'genesis'] },
  { code: 'P1765', description: 'Torque Converter Clutch Circuit', manufacturers: ['hyundai', 'kia', 'genesis'] },

  // ==================== VOLKSWAGEN / AUDI SPECIFIC ====================
  { code: 'P1102', description: 'O2 Sensor Heating Circuit (Bank 1 Sensor 1) Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1105', description: 'O2 Sensor Heating Circuit (Bank 1 Sensor 2) Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1107', description: 'O2 Sensor Heating Circuit (Bank 2 Sensor 1) Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1110', description: 'O2 Sensor Heating Circuit (Bank 2 Sensor 2) Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1111', description: 'O2 Control (Bank 1) System Too Lean', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1112', description: 'O2 Control (Bank 1) System Too Rich', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1113', description: 'O2 Control (Bank 1 Sensor 1) Internal Resistance Too High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1114', description: 'O2 Control (Bank 1 Sensor 2) Internal Resistance Too High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1115', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1) Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1116', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1) Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1117', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 2) Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1118', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 2) Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1127', description: 'Long Term Fuel Trim (Bank 1) System Too Rich', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1128', description: 'Long Term Fuel Trim (Bank 1) System Too Lean', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1129', description: 'Long Term Fuel Trim (Bank 2) System Too Rich', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1130', description: 'Long Term Fuel Trim (Bank 2) System Too Lean', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1136', description: 'Long Term Fuel Trim Add.Fuel (Bank 1) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1137', description: 'Long Term Fuel Trim Sub.Fuel (Bank 1) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1138', description: 'Long Term Fuel Trim Add.Fuel (Bank 2) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1139', description: 'Long Term Fuel Trim Sub.Fuel (Bank 2) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1141', description: 'Load Calculation Cross Check Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1171', description: 'Throttle Actuator B1 Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1176', description: 'O2 Correction Behind Catalyst (Bank 1) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1177', description: 'O2 Correction Behind Catalyst (Bank 2) Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1196', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1) Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1197', description: 'O2 Sensor Heater Circuit (Bank 2 Sensor 1) Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1213', description: 'Cylinder 1 Fuel Injector Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1214', description: 'Cylinder 2 Fuel Injector Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1215', description: 'Cylinder 3 Fuel Injector Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1216', description: 'Cylinder 4 Fuel Injector Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1225', description: 'Cylinder 1 Fuel Injector Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1226', description: 'Cylinder 2 Fuel Injector Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1227', description: 'Cylinder 3 Fuel Injector Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1228', description: 'Cylinder 4 Fuel Injector Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1237', description: 'Cylinder 1 Fuel Injector Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1238', description: 'Cylinder 2 Fuel Injector Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1239', description: 'Cylinder 3 Fuel Injector Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1240', description: 'Cylinder 4 Fuel Injector Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1250', description: 'Fuel Level Too Low', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1296', description: 'Cooling System', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1297', description: 'Connection Turbocharger Bypass Valve / Throttle Valve', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1325', description: 'Cylinder 1 Knock Control Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1326', description: 'Cylinder 2 Knock Control Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1327', description: 'Cylinder 3 Knock Control Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1328', description: 'Cylinder 4 Knock Control Limit Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1338', description: 'Cylinder 1-4 Knock Control Test Pulse', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1340', description: 'Crankshaft-/Camshaft Position Sensor Signals Out of Sequence', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1341', description: 'Ignition Coil Power Output Stage 1 Open/Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1355', description: 'Cylinder 1 Ignition Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1386', description: 'Camshaft Position Sensor A Circuit', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1387', description: 'Camshaft Position Sensor A Circuit Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1410', description: 'Tank Ventilation Valve Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1420', description: 'Secondary Air Injection Module Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1421', description: 'Secondary Air Injection Module Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1422', description: 'Secondary Air Injection System Control Valve Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1425', description: 'Tank Ventilation Valve Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1426', description: 'Tank Ventilation Valve Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1450', description: 'Secondary Air Injection System Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1451', description: 'Secondary Air Injection System Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1452', description: 'Secondary Air Injection System Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1471', description: 'EVAP Emission Control LDP Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1472', description: 'EVAP Emission Control LDP Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1473', description: 'EVAP Emission Control LDP Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1475', description: 'EVAP Emission Control LDP Circuit Signal High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1476', description: 'EVAP Emission Control LDP Circuit Signal Low', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1500', description: 'Fuel Pump Relay Electrical', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1501', description: 'Fuel Pump Relay Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1502', description: 'Fuel Pump Relay Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1512', description: 'Intake Manifold Changeover Valve Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1515', description: 'Intake Manifold Changeover Valve Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1516', description: 'Intake Manifold Changeover Valve Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1522', description: 'Intake Camshaft Control (Bank 2) Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1523', description: 'Crash Signal from Airbag Control Module', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1529', description: 'Camshaft Control Circuit Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1530', description: 'Camshaft Control Circuit Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1531', description: 'Camshaft Control Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1539', description: 'Clutch Vacuum Vent Valve Switch Incorrect Signal', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1541', description: 'Fuel Pump Relay Circuit Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1542', description: 'Throttle Actuation Potentiometer Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1543', description: 'Throttle Actuation Potentiometer Signal Too Low', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1544', description: 'Throttle Actuation Potentiometer Signal Too High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1545', description: 'Throttle Position Control Malfunction', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1546', description: 'Boost Pressure Control Valve Short to B+', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1547', description: 'Boost Pressure Control Valve Short to Ground', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1548', description: 'Boost Pressure Control Valve Open', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1555', description: 'Charge Pressure Upper Limit Exceeded', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1556', description: 'Charge Pressure Negative Deviation', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1557', description: 'Charge Pressure Positive Deviation', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1558', description: 'Throttle Actuator Electrical', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1559', description: 'Idle Speed Control Throttle Position Adaptation', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1560', description: 'Maximum Engine Speed Exceeded', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1564', description: 'Idle Speed Control Throttle Position Low Voltage During Adaptation', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1565', description: 'Idle Speed Control Throttle Position Lower Limit Not Attained', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1602', description: 'Power Supply Terminal 15 Low Voltage', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1603', description: 'Internal Control Module Malfunction', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1604', description: 'Internal Control Module Driver Error', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1609', description: 'Crash Shut-Down Activated', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1612', description: 'ECM Incorrect Coding', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1624', description: 'MIL Request Signal from TCM Active', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1626', description: 'Data Bus Powertrain Missing Message from TCM', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1631', description: 'Accelerator Position Sensor 1 Signal Too Low', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1632', description: 'Accelerator Position Sensor 1 Signal Too High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1633', description: 'Accelerator Position Sensor 2 Signal Too Low', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1634', description: 'Accelerator Position Sensor 2 Signal Too High', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1639', description: 'Accelerator Position Sensors 1+2 Range/Performance', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1640', description: 'Internal Control Module EEPROM Error', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1648', description: 'Data Bus Powertrain Missing Message from ABS', manufacturers: ['volkswagen', 'audi'] },
  { code: 'P1649', description: 'Data Bus Powertrain Missing Message from Instrument Panel', manufacturers: ['volkswagen', 'audi'] },

  // ==================== BMW / MINI SPECIFIC ====================
  { code: 'P1083', description: 'Fuel Control Mixture Lean (Bank 1 Sensor 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1084', description: 'Fuel Control Mixture Rich (Bank 1 Sensor 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1085', description: 'Fuel Control Mixture Lean (Bank 2 Sensor 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1086', description: 'Fuel Control Mixture Rich (Bank 2 Sensor 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1093', description: 'Fuel Trim 2 Sensor 1 (Bank 2)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1094', description: 'Fuel Trim 2 Sensor 2 (Bank 2)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1107', description: 'Heated Catalyst B1 Low Efficiency', manufacturers: ['bmw', 'mini'] },
  { code: 'P1108', description: 'Heated Catalyst B2 Low Efficiency', manufacturers: ['bmw', 'mini'] },
  { code: 'P1188', description: 'Fuel Mixture Control (Bank 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1189', description: 'Fuel Mixture Control (Bank 2)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1250', description: 'Fuel Pressure Regulator Control Circuit', manufacturers: ['bmw', 'mini'] },
  { code: 'P1251', description: 'Fuel Pressure Regulator Control Circuit Short to B+', manufacturers: ['bmw', 'mini'] },
  { code: 'P1252', description: 'Fuel Pressure Regulator Control Circuit Short to Ground', manufacturers: ['bmw', 'mini'] },
  { code: 'P1345', description: 'Crankshaft Position/Camshaft Position Correlation (Bank 1 Sensor A)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1349', description: 'Ignition Coil Power Output Stage', manufacturers: ['bmw', 'mini'] },
  { code: 'P1396', description: 'Camshaft Position Sensor B Circuit (Bank 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1397', description: 'Camshaft Position Sensor B Circuit (Bank 2)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1414', description: 'Secondary Air Injection System Bank 2', manufacturers: ['bmw', 'mini'] },
  { code: 'P1415', description: 'Secondary Air Injection System (Bank 2)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1423', description: 'Secondary Air Injection System (Bank 1)', manufacturers: ['bmw', 'mini'] },
  { code: 'P1443', description: 'EVAP Control System Vent Control Regulator Circuit', manufacturers: ['bmw', 'mini'] },
  { code: 'P1447', description: 'EVAP System Leak Detection Pump Solenoid Valve', manufacturers: ['bmw', 'mini'] },
  { code: 'P1501', description: 'Fuel Pump Relay Contact Malfunction', manufacturers: ['bmw', 'mini'] },
  { code: 'P1519', description: 'Intake Camshaft Control Bank 1 Malfunction', manufacturers: ['bmw', 'mini'] },
  { code: 'P1520', description: 'Intake Camshaft Control Bank 2 Malfunction', manufacturers: ['bmw', 'mini'] },
  { code: 'P1523', description: 'Intake VANOS Solenoid Bank 1 Circuit Open/Short', manufacturers: ['bmw', 'mini'] },
  { code: 'P1524', description: 'Intake VANOS Solenoid Bank 2 Circuit Open/Short', manufacturers: ['bmw', 'mini'] },
  { code: 'P1525', description: 'Exhaust VANOS Solenoid Bank 1 Circuit Open/Short', manufacturers: ['bmw', 'mini'] },
  { code: 'P1526', description: 'Exhaust VANOS Solenoid Bank 2 Circuit Open/Short', manufacturers: ['bmw', 'mini'] },
  { code: 'P1545', description: 'Throttle Valve Control Unit Malfunction', manufacturers: ['bmw', 'mini'] },
  { code: 'P1550', description: 'Idle Speed Control Error', manufacturers: ['bmw', 'mini'] },
  { code: 'P1552', description: 'Idle Speed Control Adaptation Limit', manufacturers: ['bmw', 'mini'] },
  { code: 'P1555', description: 'Electronic Throttle Control', manufacturers: ['bmw', 'mini'] },
  { code: 'P1601', description: 'Internal Control Module Memory Error', manufacturers: ['bmw', 'mini'] },
  { code: 'P1612', description: 'ECM Programming Error', manufacturers: ['bmw', 'mini'] },
  { code: 'P1614', description: 'Fault Code Memory Checksum Error', manufacturers: ['bmw', 'mini'] },
  { code: 'P1624', description: 'MIL Request Signal Active from TCM', manufacturers: ['bmw', 'mini'] },
  { code: 'P1689', description: 'Internal Control Module Random Access Memory Error', manufacturers: ['bmw', 'mini'] },

  // ==================== MERCEDES-BENZ SPECIFIC ====================
  { code: 'P1105', description: 'Supercharger Bypass Solenoid', manufacturers: ['mercedes'] },
  { code: 'P1107', description: 'Barometric Pressure Sensor Circuit Low', manufacturers: ['mercedes'] },
  { code: 'P1108', description: 'Barometric Pressure Sensor Circuit High', manufacturers: ['mercedes'] },
  { code: 'P1120', description: 'Accelerator Pedal Position Sensor 2 Circuit', manufacturers: ['mercedes'] },
  { code: 'P1127', description: 'O2 Sensor Heating Circuit (Bank 1 Sensor 2) Short', manufacturers: ['mercedes'] },
  { code: 'P1130', description: 'O2 Sensor Signal Voltage Stuck Lean (Bank 1 Sensor 1)', manufacturers: ['mercedes'] },
  { code: 'P1133', description: 'O2 Sensor Response Time Slow (Bank 1 Sensor 1)', manufacturers: ['mercedes'] },
  { code: 'P1137', description: 'O2 Sensor Low Voltage (Bank 1 Sensor 2)', manufacturers: ['mercedes'] },
  { code: 'P1171', description: 'Fuel System Lean During Acceleration', manufacturers: ['mercedes'] },
  { code: 'P1186', description: 'O2 Sensor Heater Circuit Performance (Bank 2 Sensor 1)', manufacturers: ['mercedes'] },
  { code: 'P1187', description: 'O2 Sensor Heater Circuit Performance (Bank 2 Sensor 2)', manufacturers: ['mercedes'] },
  { code: 'P1189', description: 'Fuel Shut-Off Valve Circuit (Bank 1)', manufacturers: ['mercedes'] },
  { code: 'P1190', description: 'Fuel Shut-Off Valve Circuit (Bank 2)', manufacturers: ['mercedes'] },
  { code: 'P1200', description: 'Injector Control Circuit', manufacturers: ['mercedes'] },
  { code: 'P1220', description: 'Throttle Position Sensor B Circuit', manufacturers: ['mercedes'] },
  { code: 'P1221', description: 'Throttle Position Sensor B Circuit Range/Performance', manufacturers: ['mercedes'] },
  { code: 'P1235', description: 'Fuel Pump Control Module', manufacturers: ['mercedes'] },
  { code: 'P1250', description: 'Fuel Pressure Regulator Control Circuit', manufacturers: ['mercedes'] },
  { code: 'P1336', description: 'Crankshaft Position Sensor Circuit Intermittent', manufacturers: ['mercedes'] },
  { code: 'P1340', description: 'Camshaft/Crankshaft Position Sensor Signals Out of Sequence', manufacturers: ['mercedes'] },
  { code: 'P1386', description: 'Knock Control Test Pulse', manufacturers: ['mercedes'] },
  { code: 'P1400', description: 'EGR Position Sensor Circuit', manufacturers: ['mercedes'] },
  { code: 'P1401', description: 'EGR Position Sensor Performance', manufacturers: ['mercedes'] },
  { code: 'P1421', description: 'Secondary Air Injection System Switching Valve (Bank 1)', manufacturers: ['mercedes'] },
  { code: 'P1422', description: 'Secondary Air Injection System Switching Valve (Bank 2)', manufacturers: ['mercedes'] },
  { code: 'P1455', description: 'A/C Evaporator Temperature Sensor Circuit', manufacturers: ['mercedes'] },
  { code: 'P1470', description: 'Leak Detection Pump Solenoid Circuit', manufacturers: ['mercedes'] },
  { code: 'P1500', description: 'Starter Motor Signal Circuit', manufacturers: ['mercedes'] },
  { code: 'P1519', description: 'Intake Manifold Runner Control Stuck Open', manufacturers: ['mercedes'] },
  { code: 'P1542', description: 'Throttle Actuator Control Circuit', manufacturers: ['mercedes'] },
  { code: 'P1545', description: 'Throttle Position Control Malfunction', manufacturers: ['mercedes'] },
  { code: 'P1570', description: 'Engine Immobilizer System', manufacturers: ['mercedes'] },
  { code: 'P1580', description: 'Throttle Valve Actuator Circuit', manufacturers: ['mercedes'] },
  { code: 'P1600', description: 'Internal ECM/PCM Error', manufacturers: ['mercedes'] },
  { code: 'P1604', description: 'ECM/PCM Internal CPU Error', manufacturers: ['mercedes'] },
  { code: 'P1607', description: 'ECM/PCM Internal Circuit A', manufacturers: ['mercedes'] },
  { code: 'P1630', description: 'APP Sensor 1-2 Correlation', manufacturers: ['mercedes'] },
  { code: 'P1640', description: 'ECM/PCM Internal Control Module', manufacturers: ['mercedes'] },
  { code: 'P1747', description: 'Electronic Pressure Control Solenoid', manufacturers: ['mercedes'] },

  // ==================== FORD / LINCOLN SPECIFIC ====================
  { code: 'P1000', description: 'OBD Systems Readiness Test Not Complete', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1100', description: 'Mass Air Flow Sensor Intermittent', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1101', description: 'Mass Air Flow Sensor Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1112', description: 'Intake Air Temperature Sensor Intermittent', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1116', description: 'Engine Coolant Temperature Sensor Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1117', description: 'Engine Coolant Temperature Sensor Intermittent', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1120', description: 'Throttle Position Sensor Out of Range Low', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1121', description: 'Throttle Position Sensor Inconsistent with MAF Sensor', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1124', description: 'Throttle Position Sensor Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1125', description: 'Throttle Position Sensor Intermittent', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1127', description: 'Exhaust Not Warm Enough, Downstream Heated O2 Sensors Not Tested', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1128', description: 'Upstream Heated O2 Sensors Swapped', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1129', description: 'Downstream Heated O2 Sensors Swapped', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1130', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1131', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1132', description: 'Lack of Heated O2 Switch - Sensor Indicates Rich (Bank 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1137', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 1 Sensor 2)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1138', description: 'Lack of Heated O2 Switch - Sensor Indicates Rich (Bank 1 Sensor 2)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1150', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 2 Sensor 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1151', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 2 Sensor 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1152', description: 'Lack of Heated O2 Switch - Sensor Indicates Rich (Bank 2 Sensor 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1157', description: 'Lack of Heated O2 Switch - Sensor Indicates Lean (Bank 2 Sensor 2)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1158', description: 'Lack of Heated O2 Switch - Sensor Indicates Rich (Bank 2 Sensor 2)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1220', description: 'Series Throttle Control System', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1221', description: 'Traction Control System', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1230', description: 'Fuel Pump Primary Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1231', description: 'Fuel Pump Secondary Circuit Low, High Speed Fuel Pump On', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1232', description: 'Low Speed Fuel Pump Primary Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1233', description: 'Fuel Pump Driver Module Off-Line', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1234', description: 'Fuel Pump Driver Module Off-Line', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1235', description: 'Fuel Pump Control Out of Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1236', description: 'Fuel Pump Control Out of Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1237', description: 'Fuel Pump Secondary Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1238', description: 'Fuel Pump Secondary Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1260', description: 'Theft Detected - Vehicle Immobilized', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1270', description: 'Engine RPM or Vehicle Speed Limiter Reached', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1285', description: 'Cylinder Head Temperature Over Temperature Detected', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1288', description: 'Cylinder Head Temperature Sensor Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1289', description: 'Cylinder Head Temperature Sensor High', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1290', description: 'Cylinder Head Temperature Sensor Low', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1299', description: 'Cylinder Head Over Temperature Protection Active', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1309', description: 'Misfire Detection Monitor Not Enabled', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1336', description: 'CKP/CMP Sensor Correlation', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1340', description: 'Camshaft Position Sensor A/B Correlation (Bank 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1345', description: 'Crankshaft Position/Camshaft Position Correlation', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1400', description: 'DPFE Sensor Circuit Low Input', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1401', description: 'DPFE Sensor Circuit High Input', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1405', description: 'DPFE Sensor Upstream Hose Off or Plugged', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1406', description: 'DPFE Sensor Downstream Hose Off or Plugged', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1408', description: 'EGR Flow Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1409', description: 'EGR Vacuum Regulator Solenoid Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1442', description: 'EVAP System Small Leak Detected', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1443', description: 'EVAP System Canister Vent Solenoid Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1444', description: 'EVAP Canister Purge Solenoid Output Low', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1450', description: 'Unable to Bleed Up Fuel Tank Vacuum', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1451', description: 'EVAP Emission Control System Vent Control Malfunction', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1455', description: 'EVAP System Gross Leak / No Flow', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1460', description: 'Wide Open Throttle Air Conditioning Cutoff Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1461', description: 'Air Conditioning Pressure Sensor High Voltage', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1462', description: 'Air Conditioning Pressure Sensor Low Voltage', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1463', description: 'Air Conditioning Pressure Sensor Insufficient Pressure Change', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1464', description: 'Air Conditioning Clutch Relay Output Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1469', description: 'Low Air Conditioning Cycling Period', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1473', description: 'Fan Secondary High With Fan(s) Off', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1474', description: 'Low Fan Control Primary Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1500', description: 'Vehicle Speed Sensor Intermittent', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1501', description: 'Vehicle Speed Sensor Out of Self-Test Range', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1504', description: 'Idle Air Control Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1505', description: 'Idle Air Control System at Adaptive Clip', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1506', description: 'Idle Air Control Over-Speed Error', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1507', description: 'Idle Air Control Under-Speed Error', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1518', description: 'Intake Manifold Runner Control Stuck Open', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1519', description: 'Intake Manifold Runner Control Stuck Closed', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1520', description: 'Intake Manifold Runner Control Circuit', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1537', description: 'Intake Manifold Runner Control Stuck Open (Bank 1)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1538', description: 'Intake Manifold Runner Control Stuck Open (Bank 2)', manufacturers: ['ford', 'lincoln'] },
  { code: 'P1539', description: 'A/C Clutch Circuit / Power to Ground Short', manufacturers: ['ford', 'lincoln'] },

  // ==================== CHEVROLET / GMC / CADILLAC / BUICK SPECIFIC ====================
  { code: 'P1031', description: 'HO2S Heater Current Monitor Control Circuit (Bank 1 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1032', description: 'HO2S Heater Warm Up Control Circuit (Bank 1 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1105', description: 'Secondary Vacuum Sensor Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1106', description: 'MAP Sensor Circuit Intermittent High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1107', description: 'MAP Sensor Circuit Intermittent Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1111', description: 'IAT Sensor Circuit Intermittent High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1112', description: 'IAT Sensor Circuit Intermittent Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1114', description: 'ECT Sensor Circuit Intermittent Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1115', description: 'ECT Sensor Circuit Intermittent High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1120', description: 'TP Sensor 1 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1121', description: 'TP Sensor Circuit Intermittent High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1122', description: 'TP Sensor Circuit Intermittent Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1125', description: 'Accelerator Pedal Position System', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1133', description: 'HO2S Insufficient Switching (Bank 1 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1134', description: 'HO2S Transition Time Ratio (Bank 1 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1153', description: 'HO2S Insufficient Switching (Bank 2 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1154', description: 'HO2S Transition Time Ratio (Bank 2 Sensor 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1171', description: 'Fuel System Lean During Acceleration', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1187', description: 'Engine Oil Temperature Sensor Circuit Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1188', description: 'Engine Oil Temperature Sensor Circuit High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1189', description: 'Engine Oil Pressure Switch Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1200', description: 'Injector Control Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1220', description: 'Throttle Position Sensor 2 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1221', description: 'TP Sensor 1-2 Correlation', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1258', description: 'Engine Coolant Over Temperature Protection Mode Active', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1260', description: 'Last Test Failed SCC Or Theft Detected Fuel Disable', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1271', description: 'Accelerator Pedal Position Sensor 1-2 Correlation', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1275', description: 'Accelerator Pedal Position Sensor 1 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1276', description: 'Accelerator Pedal Position Sensor 1 Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1280', description: 'Accelerator Pedal Position Sensor 2 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1281', description: 'Accelerator Pedal Position Sensor 2 Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1336', description: 'Crankshaft Position Sensor System Variation Not Learned', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1345', description: 'Crankshaft/Camshaft Position Correlation', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1351', description: 'Ignition Control Circuit High Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1361', description: 'Ignition Control Circuit Low Voltage', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1380', description: 'Misfire Detected - Rough Road Data Not Available', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1381', description: 'Misfire Detected - No Communication with BCM', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1404', description: 'EGR Valve Pintle Stuck Open', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1406', description: 'EGR Valve Pintle Position Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1415', description: 'Secondary Air Injection System (Bank 1)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1416', description: 'Secondary Air Injection System (Bank 2)', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1441', description: 'EVAP System Flow During Non-Purge', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1508', description: 'Idle Speed Control System Low RPM', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1509', description: 'Idle Speed Control System High RPM', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1514', description: 'Electronic Throttle Control Module Throttle Actuator Position Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1515', description: 'Electronic Throttle Control Module Throttle Body Position Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1516', description: 'Electronic Throttle Control Module Throttle Actuator Control Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1517', description: 'Electronic Throttle Control Module Throttle Actuator Control Circuit Low', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1518', description: 'Electronic Throttle Control Module Throttle Actuator Control Circuit High', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1621', description: 'PCM Memory Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1626', description: 'Theft Deterrent Fuel Enable Signal Lost', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1627', description: 'A/D Performance', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1628', description: 'ECM/PCM/VCM Unauthorized Software', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1629', description: 'Theft Deterrent System - Cranking Signal', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1635', description: '5 Volt Reference 1 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1637', description: 'Generator L-Terminal Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1638', description: 'Generator F-Terminal Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1639', description: '5 Volt Reference 2 Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1641', description: 'MIL Control Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },
  { code: 'P1689', description: 'Traction Control Delivered Torque Output Circuit', manufacturers: ['chevrolet', 'gmc', 'cadillac', 'buick'] },

  // ==================== MAZDA SPECIFIC ====================
  { code: 'P1100', description: 'MAF Sensor Circuit Intermittent', manufacturers: ['mazda'] },
  { code: 'P1101', description: 'MAF Sensor Out of Self Test Range', manufacturers: ['mazda'] },
  { code: 'P1117', description: 'ECT Sensor Intermittent', manufacturers: ['mazda'] },
  { code: 'P1125', description: 'Throttle Position Sensor Intermittent', manufacturers: ['mazda'] },
  { code: 'P1131', description: 'HO2S (Bank 1 Sensor 1) Lean Shift Monitoring', manufacturers: ['mazda'] },
  { code: 'P1132', description: 'HO2S (Bank 1 Sensor 1) Rich Shift Monitoring', manufacturers: ['mazda'] },
  { code: 'P1151', description: 'HO2S (Bank 2 Sensor 1) Lean Shift Monitoring', manufacturers: ['mazda'] },
  { code: 'P1152', description: 'HO2S (Bank 2 Sensor 1) Rich Shift Monitoring', manufacturers: ['mazda'] },
  { code: 'P1195', description: 'Barometric Pressure Sensor Circuit Low', manufacturers: ['mazda'] },
  { code: 'P1196', description: 'Barometric Pressure Sensor Circuit High', manufacturers: ['mazda'] },
  { code: 'P1229', description: 'CPC Solenoid Valve B Circuit Open/Short', manufacturers: ['mazda'] },
  { code: 'P1230', description: 'Fuel Pump Relay Circuit', manufacturers: ['mazda'] },
  { code: 'P1260', description: 'Theft Detected - Engine Disabled', manufacturers: ['mazda'] },
  { code: 'P1309', description: 'Misfire Detection Monitor Not Active', manufacturers: ['mazda'] },
  { code: 'P1345', description: 'Crankshaft Position/Camshaft Position Correlation', manufacturers: ['mazda'] },
  { code: 'P1380', description: 'Variable Valve Timing Solenoid A Circuit (Bank 1)', manufacturers: ['mazda'] },
  { code: 'P1381', description: 'Variable Valve Timing Stuck in Off Position (Bank 1)', manufacturers: ['mazda'] },
  { code: 'P1383', description: 'Variable Valve Timing System Range/Performance (Bank 1)', manufacturers: ['mazda'] },
  { code: 'P1400', description: 'EGR Valve Position Sensor Circuit', manufacturers: ['mazda'] },
  { code: 'P1401', description: 'EGR Temperature Sensor Circuit', manufacturers: ['mazda'] },
  { code: 'P1408', description: 'EGR Flow Out of Range', manufacturers: ['mazda'] },
  { code: 'P1443', description: 'EVAP Control System Vent Control Malfunction', manufacturers: ['mazda'] },
  { code: 'P1450', description: 'Excessive Vacuum Leak (Fuel Tank Pressure)', manufacturers: ['mazda'] },
  { code: 'P1451', description: 'EVAP System Canister Vent Control Malfunction', manufacturers: ['mazda'] },
  { code: 'P1455', description: 'EVAP System Leak (Fuel Tank Area)', manufacturers: ['mazda'] },
  { code: 'P1460', description: 'A/C Pressure Sensor Signal', manufacturers: ['mazda'] },
  { code: 'P1474', description: 'Cooling Fan Control', manufacturers: ['mazda'] },
  { code: 'P1504', description: 'Idle Air Control Circuit', manufacturers: ['mazda'] },
  { code: 'P1506', description: 'Idle Air Control Overspeed', manufacturers: ['mazda'] },
  { code: 'P1507', description: 'Idle Air Control Underspeed', manufacturers: ['mazda'] },
  { code: 'P1517', description: 'IMRC Stuck Closed (Bank 1)', manufacturers: ['mazda'] },
  { code: 'P1518', description: 'IMRC Stuck Open (Bank 1)', manufacturers: ['mazda'] },
  { code: 'P1519', description: 'IMRC Stuck Closed (Bank 2)', manufacturers: ['mazda'] },
  { code: 'P1520', description: 'IMRC Stuck Open (Bank 2)', manufacturers: ['mazda'] },
  { code: 'P1601', description: 'PCM Serial Communication Error', manufacturers: ['mazda'] },
  { code: 'P1602', description: 'PCM Not Programmed', manufacturers: ['mazda'] },
  { code: 'P1605', description: 'PCM Keep Alive Memory Test Error', manufacturers: ['mazda'] },
  { code: 'P1633', description: 'KAM Not Loaded, Low Battery Voltage', manufacturers: ['mazda'] },
  { code: 'P1650', description: 'Power Steering Pressure Switch Out of Range', manufacturers: ['mazda'] },
  { code: 'P1703', description: 'Brake On/Off Switch Out of Range', manufacturers: ['mazda'] },
  { code: 'P1705', description: 'Transmission Range Sensor Out of Range', manufacturers: ['mazda'] },

  // ==================== SUBARU SPECIFIC ====================
  { code: 'P1086', description: 'Tumble Generation Valve Position Sensor 1 Circuit High', manufacturers: ['subaru'] },
  { code: 'P1087', description: 'Tumble Generation Valve Position Sensor 2 Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1088', description: 'Tumble Generation Valve Position Sensor 2 Circuit High', manufacturers: ['subaru'] },
  { code: 'P1089', description: 'Tumble Generation Valve System', manufacturers: ['subaru'] },
  { code: 'P1090', description: 'Tumble Generation Valve Position Sensor 1 Circuit Low (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1091', description: 'Tumble Generation Valve Position Sensor 1 Circuit High (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1092', description: 'Tumble Generation Valve Position Sensor 2 Circuit Low (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1093', description: 'Tumble Generation Valve Position Sensor 2 Circuit High (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1094', description: 'Tumble Generation Valve System (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1110', description: 'Atmospheric Pressure Sensor Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1111', description: 'Atmospheric Pressure Sensor Circuit High', manufacturers: ['subaru'] },
  { code: 'P1152', description: 'A/F Sensor Range/Performance (Bank 1 Sensor 1)', manufacturers: ['subaru'] },
  { code: 'P1160', description: 'A/F Sensor (Bank 1 Sensor 1) Low', manufacturers: ['subaru'] },
  { code: 'P1161', description: 'A/F Sensor (Bank 1 Sensor 1) High', manufacturers: ['subaru'] },
  { code: 'P1400', description: 'Fuel Tank Pressure Solenoid Control Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1410', description: 'Secondary Air Injection System Switching Valve', manufacturers: ['subaru'] },
  { code: 'P1418', description: 'Secondary Air Injection System Control Valve Circuit High', manufacturers: ['subaru'] },
  { code: 'P1420', description: 'Fuel Tank Pressure Control Solenoid Low', manufacturers: ['subaru'] },
  { code: 'P1440', description: 'EVAP Pressure System Leak Detection', manufacturers: ['subaru'] },
  { code: 'P1441', description: 'EVAP Pressure System Small Leak', manufacturers: ['subaru'] },
  { code: 'P1442', description: 'Fuel Level Sensor Circuit', manufacturers: ['subaru'] },
  { code: 'P1443', description: 'EVAP Emission Control System Vent Control Malfunction', manufacturers: ['subaru'] },
  { code: 'P1491', description: 'PCV Blow-By Function', manufacturers: ['subaru'] },
  { code: 'P1492', description: 'EGR Solenoid Valve Circuit High', manufacturers: ['subaru'] },
  { code: 'P1493', description: 'EGR Solenoid Valve Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1494', description: 'EGR Solenoid Valve Circuit Open', manufacturers: ['subaru'] },
  { code: 'P1495', description: 'EGR Solenoid Valve Circuit', manufacturers: ['subaru'] },
  { code: 'P1497', description: 'EGR Solenoid Valve Function Low', manufacturers: ['subaru'] },
  { code: 'P1498', description: 'EGR Solenoid Valve Function High', manufacturers: ['subaru'] },
  { code: 'P1499', description: 'EGR Solenoid Valve System', manufacturers: ['subaru'] },
  { code: 'P1512', description: 'Intake Manifold Switching Valve', manufacturers: ['subaru'] },
  { code: 'P1513', description: 'Intake Manifold Switching Valve Circuit High', manufacturers: ['subaru'] },
  { code: 'P1514', description: 'Intake Manifold Switching Valve Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1516', description: 'Intake Manifold Switching Valve (Bank 2)', manufacturers: ['subaru'] },
  { code: 'P1518', description: 'Starter Switch Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1519', description: 'IMRC Stuck Closed', manufacturers: ['subaru'] },
  { code: 'P1520', description: 'Starter Switch Circuit High', manufacturers: ['subaru'] },
  { code: 'P1544', description: 'Exhaust Gas Temperature Too High', manufacturers: ['subaru'] },
  { code: 'P1560', description: 'Backup Voltage Malfunction', manufacturers: ['subaru'] },
  { code: 'P1602', description: 'Neutral Position Switch Circuit Low', manufacturers: ['subaru'] },
  { code: 'P1604', description: 'Starter Switch Circuit', manufacturers: ['subaru'] },

  // ==================== MITSUBISHI SPECIFIC ====================
  { code: 'P1100', description: 'Induction Control Motor Position Sensor', manufacturers: ['mitsubishi'] },
  { code: 'P1101', description: 'Tumble Valve Position Sensor', manufacturers: ['mitsubishi'] },
  { code: 'P1102', description: 'Tumble Generator Valve Position Sensor', manufacturers: ['mitsubishi'] },
  { code: 'P1104', description: 'Tumble Generator Valve Stuck Open', manufacturers: ['mitsubishi'] },
  { code: 'P1105', description: 'Fuel Pressure Solenoid', manufacturers: ['mitsubishi'] },
  { code: 'P1220', description: 'Fuel Pressure Solenoid #2', manufacturers: ['mitsubishi'] },
  { code: 'P1225', description: 'Barometric Pressure Sensor Circuit High', manufacturers: ['mitsubishi'] },
  { code: 'P1226', description: 'Barometric Pressure Sensor Circuit Low', manufacturers: ['mitsubishi'] },
  { code: 'P1227', description: 'Barometric Pressure Sensor Range/Performance', manufacturers: ['mitsubishi'] },
  { code: 'P1255', description: 'Radiator Temp Signal Missing', manufacturers: ['mitsubishi'] },
  { code: 'P1295', description: 'No 5V Supply to TP Sensor', manufacturers: ['mitsubishi'] },
  { code: 'P1296', description: 'No 5V Supply to MAP Sensor', manufacturers: ['mitsubishi'] },
  { code: 'P1297', description: 'No Change in MAP From Start to Run', manufacturers: ['mitsubishi'] },
  { code: 'P1300', description: 'Ignition Timing Adjustment Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1310', description: 'IC Power Transistor #1', manufacturers: ['mitsubishi'] },
  { code: 'P1320', description: 'IC Power Transistor #2', manufacturers: ['mitsubishi'] },
  { code: 'P1330', description: 'IC Power Transistor #3', manufacturers: ['mitsubishi'] },
  { code: 'P1340', description: 'IC Power Transistor #4', manufacturers: ['mitsubishi'] },
  { code: 'P1386', description: 'Knock Sensor Control Zero Test', manufacturers: ['mitsubishi'] },
  { code: 'P1400', description: 'MDP Sensor Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1443', description: 'EVAP Emission Control System Vent Control Malfunction', manufacturers: ['mitsubishi'] },
  { code: 'P1449', description: 'EVAP Emission Control System Vent Control Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1486', description: 'EGR Vacuum Solenoid Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1487', description: 'EGR Boost Sensor Solenoid Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1489', description: 'EGR Solenoid Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1500', description: 'Generator FR Terminal Circuit', manufacturers: ['mitsubishi'] },
  { code: 'P1600', description: 'Serial Communication Link', manufacturers: ['mitsubishi'] },
  { code: 'P1610', description: 'Immobilizer System - ECU Authentication Failed', manufacturers: ['mitsubishi'] },
  { code: 'P1611', description: 'Immobilizer System - Key Code Mismatch', manufacturers: ['mitsubishi'] },
  { code: 'P1612', description: 'Immobilizer System - ECU ID Not Registered', manufacturers: ['mitsubishi'] },
  { code: 'P1613', description: 'Immobilizer System - Communication Error', manufacturers: ['mitsubishi'] },
  { code: 'P1614', description: 'Immobilizer System - Key Transponder Error', manufacturers: ['mitsubishi'] },
  { code: 'P1750', description: 'Solenoid Assembly', manufacturers: ['mitsubishi'] },
  { code: 'P1751', description: 'CVT Judder', manufacturers: ['mitsubishi'] },

  // ==================== VOLVO SPECIFIC ====================
  { code: 'P1031', description: 'O2 Sensor Heating, Front', manufacturers: ['volvo'] },
  { code: 'P1032', description: 'O2 Sensor Heating, Rear', manufacturers: ['volvo'] },
  { code: 'P1105', description: 'Mass Air Flow Sensor Adaptation', manufacturers: ['volvo'] },
  { code: 'P1110', description: 'Mass Air Flow Sensor Fault', manufacturers: ['volvo'] },
  { code: 'P1151', description: 'O2 Sensor Pre-Cat (Bank 2) No Activity', manufacturers: ['volvo'] },
  { code: 'P1152', description: 'O2 Sensor Pre-Cat (Bank 2) Too Lean', manufacturers: ['volvo'] },
  { code: 'P1171', description: 'System Too Lean At Cruise', manufacturers: ['volvo'] },
  { code: 'P1172', description: 'System Too Rich At Cruise', manufacturers: ['volvo'] },
  { code: 'P1270', description: 'Speed Limitation Function Activated', manufacturers: ['volvo'] },
  { code: 'P1273', description: 'Short to B+ in A/F Ratio Sensor', manufacturers: ['volvo'] },
  { code: 'P1274', description: 'Short to Ground in A/F Ratio Sensor', manufacturers: ['volvo'] },
  { code: 'P1275', description: 'A/F Sensor Slow Response (Bank 1)', manufacturers: ['volvo'] },
  { code: 'P1276', description: 'A/F Sensor No Activity (Bank 1)', manufacturers: ['volvo'] },
  { code: 'P1294', description: 'Target Idle Speed Not Reached', manufacturers: ['volvo'] },
  { code: 'P1335', description: 'Engine Camshaft Position Signal Missing', manufacturers: ['volvo'] },
  { code: 'P1380', description: 'Long Term Fuel Trim At Rich Limit (Bank 1)', manufacturers: ['volvo'] },
  { code: 'P1381', description: 'Long Term Fuel Trim At Lean Limit (Bank 1)', manufacturers: ['volvo'] },
  { code: 'P1382', description: 'Long Term Fuel Trim At Rich Limit (Bank 2)', manufacturers: ['volvo'] },
  { code: 'P1383', description: 'Long Term Fuel Trim At Lean Limit (Bank 2)', manufacturers: ['volvo'] },
  { code: 'P1400', description: 'ECM Relay (Driver Side)', manufacturers: ['volvo'] },
  { code: 'P1410', description: 'Tank Leakage Diagnosis Pump', manufacturers: ['volvo'] },
  { code: 'P1441', description: 'EVAP System Large Leak', manufacturers: ['volvo'] },
  { code: 'P1442', description: 'EVAP System Small Leak', manufacturers: ['volvo'] },
  { code: 'P1455', description: 'A/C Pressure Sensor Signal Missing', manufacturers: ['volvo'] },
  { code: 'P1500', description: 'ECM Control Relay Output Low', manufacturers: ['volvo'] },
  { code: 'P1501', description: 'ECM Control Relay Output High', manufacturers: ['volvo'] },
  { code: 'P1510', description: 'EVAP Solenoid Circuit', manufacturers: ['volvo'] },
  { code: 'P1530', description: 'A/C Clutch Relay Control Circuit', manufacturers: ['volvo'] },
  { code: 'P1545', description: 'Throttle Position Sensor Adaptation Error', manufacturers: ['volvo'] },
  { code: 'P1549', description: 'Boost Pressure Sensor Fault', manufacturers: ['volvo'] },
  { code: 'P1556', description: 'Charge Air Pressure Sensor Fault', manufacturers: ['volvo'] },
  { code: 'P1603', description: 'EEPROM Malfunction', manufacturers: ['volvo'] },
  { code: 'P1606', description: 'Control Module Self Test, Torque Monitoring', manufacturers: ['volvo'] },
  { code: 'P1618', description: 'SAS Signal Missing', manufacturers: ['volvo'] },
  { code: 'P1693', description: 'Turbo Control Valve Signal', manufacturers: ['volvo'] },
];

/**
 * Get manufacturer-specific DTC description
 * @param code DTC code
 * @param manufacturerId Manufacturer ID
 * @param year Vehicle year (optional)
 * @returns Description or null if not found
 */
export function getManufacturerDTCDescription(
  code: string,
  manufacturerId: string,
  year?: number
): string | null {
  const entry = MANUFACTURER_DTC_CODES.find((dtc) => {
    if (dtc.code !== code) return false;
    if (!dtc.manufacturers.includes(manufacturerId)) return false;
    
    // Check year range if specified
    if (year && dtc.yearRange) {
      if (dtc.yearRange.start && year < dtc.yearRange.start) return false;
      if (dtc.yearRange.end && year > dtc.yearRange.end) return false;
    }
    
    return true;
  });

  return entry?.description || null;
}

/**
 * Get all DTCs for a specific manufacturer
 * @param manufacturerId Manufacturer ID
 * @returns Array of DTCs for that manufacturer
 */
export function getManufacturerDTCs(manufacturerId: string): ManufacturerDTCEntry[] {
  return MANUFACTURER_DTC_CODES.filter((dtc) => 
    dtc.manufacturers.includes(manufacturerId)
  );
}

/**
 * Check if a DTC code is manufacturer-specific
 * A code is typically manufacturer-specific if it's in the P1xxx, P3xxx, 
 * B1xxx, C1xxx, or U1xxx range
 */
export function isManufacturerSpecificCode(code: string): boolean {
  if (!code || code.length < 5) return false;
  
  const prefix = code.charAt(0).toUpperCase();
  const firstDigit = parseInt(code.charAt(1), 10);
  
  // P1xxx, P3xxx are manufacturer-specific powertrain codes
  if (prefix === 'P' && (firstDigit === 1 || firstDigit === 3)) return true;
  
  // B1xxx, B2xxx are manufacturer-specific body codes
  if (prefix === 'B' && (firstDigit === 1 || firstDigit === 2)) return true;
  
  // C1xxx, C2xxx are manufacturer-specific chassis codes
  if (prefix === 'C' && (firstDigit === 1 || firstDigit === 2)) return true;
  
  // U1xxx, U2xxx are manufacturer-specific network codes
  if (prefix === 'U' && (firstDigit === 1 || firstDigit === 2)) return true;
  
  return false;
}
